name: "Test Sample Schedules"

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '10 * * * *'
    
jobs:
  terraform_schedule:
    name: "Test Actions Schedules"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./xc
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check time
        run: |
          git checkout bot-defense-re
          git commit --allow-empty -m "Empty-Commit"
          git push origin
