name: "Test Sample Schedules"

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '10 * * * *'
    
jobs:
  terraform_xc_lb:
    name: "Test Actions Schedules"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./xc
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Workflow
        uses: https://github.com/janibashamd/f5-xc-terraform-examples/blob/bot-defense-re/.github/workflows/bot-defense-re-deploy.yaml@bot-defense-re
