name: "Test Sample Schedules"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'
    
jobs:
  terraform_schedule:
    name: "Test Actions Schedules"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./xc
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: bot-defense-re

      - name: Trigger workflow
        run: gh workflow run bot-defense-re-deploy.yaml --ref bot-defense-re
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_SECRET }}   
      
      # - name: Add Email
      #   run: git config user.email @${{ github.actor }}

      # - name: Add Username
      #   run: git config user.name @${{ github.actor }}
  
      # - name: Create Empty Commit
      #   run: git commit --allow-empty -m "Empty commit4"
  
      # - name: Push Empty Commit
      #   run: git push origin bot-defense-re
      #   env:
      #     GH_TOKEN: ${{ secrets.ACTIONS_SECRET }}     
          
