name: "Test and Destroy Workflows"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: '10 * * * *'
#    - cron: '30 * * * *'
    
jobs:
  terraform_schedule:
    name: "Test Actions Schedules"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger Deploy workflow
        run: gh workflow run bot-defense-re-deploy.yaml --ref bot-defense-re
        if: github.event.schedule == '10 * * * *'
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_SECRET }}   

      - name: Trigger Destroy workflow
        run: gh workflow run bot-defense-re-destroy.yaml --ref destroy-bot-defense-re
        if: github.event.schedule == '30 * * * *' 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check EventName
        run: echo "event name is:" ${{ github.event_name }} 
    
