name: "Test Sample Schedules"

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '10 * * * *'
    
jobs:
  terraform_schedule:
    name: "Test Actions Schedules"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./xc
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: bot-defense-re
          
      - name: Check time
        run: |
          git config --global user.email @${{ github.actor }}
          git config --global user.name @${{ github.actor }}        
          git commit --allow-empty -m "Empty-Commit"
          git push origin
